### ISSUE TITLE
Cropping in 1080i mode

### ISSUE THREAD

**Issue by StarWolf3000** [cuevavirus/Sharpscale#1]
> 
> 1080i: integer scale the framebuffer to 1920x1088 and trim the bottom 8 lines
>
Wouldn't it be better to trim the top and bottom 4 lines in this case? Or what is the reason to decide to crop the bottom 8 lines?
Because depending on the game this might cut away important content from the game.

**Comment by MessiahMozgus** [comment]
Came here to ask the same thing.

**Comment by cuevavirus** [comment]
Yes I plan to make the trimming configurable.

**Comment by xYuunaX** [comment]
I would like to apologize in advance, If I'm asking a stupid question? I'm not an expert on any of this, but just curious on how this 'integer scale' works.. so I'm assuming that you have to keep the same aspect ratio of the vita resolution (30:17), so wouldn't it be better to use 1906x1080, having 2 small borders on the sides? so nothing needs to be trimmed or cropped?

**Comment by cuevavirus** [comment]
Integer scaling happens when the width and height are multiplied by an integer. 1920x1088 is exactly two times 960x544. In this case each pixel is scaled to exactly a 4 pixel square with no blurring.

**Comment by LittleStinky123** [comment]
Is it impossible to output 1080p because of hardware constraints? 
1080i is just right from the size, but the interlacing isn't that great.

**Comment by cuevavirus** [comment]
1080p possible in 30hz. I'll add that in the next version

**Comment by soarqin** [comment]
made a patch to crop top/bottom 4px in 1080i mode, compiled skprx: [sharpscale.zip](https://github.com/cuevavirus/Sharpscale/files/4430834/sharpscale.zip)

patch:
```
diff --git a/main.c.orig b/main.c
index e59c612..9540cd4 100644
--- a/main.c.orig
+++ b/main.c
@@ -79,6 +79,7 @@ static int sceIftuSetInputFrameBuffer_hook(int plane, SceIftuPlaneState *state,
 		state->dst_y = (720 - 544) / 2;
 	} else if (state->src_w == 0x8000 && state->src_h == 0x80F3) {
 		state->src_h = state->src_w;
+		state->src_y = 0x79;
 	}
 	return TAI_CONTINUE(int, hook_ref[0], plane, state, mask, mode);
 }
```

**Comment by cuevavirus** [comment]
@soarqin how did you arrive at 0x79? it doesn't do anything btw

**Comment by soarqin** [comment]
@cuevavirus 0x80F3 = 0x8000 * 1088 / 1080, so I think the px is scaled to 0x8000 with factor 0x8000 / 1080, so I just do 4 * 0x8000 / 1080 = 0x79

**Comment by cuevavirus** [comment]
src_w and src_h are computed like this

```
0x8000 = 0x10000 * 960 / 1920
0x80F3 = 0x10000 * 544 / 1080
```

**Comment by soarqin** [comment]
@cuevavirus yeah, so 4 px in 1920x1088 is scaled up from 2 px in 960x544, which is calculated with the same result: 0x10000 * 2 / 1080 = 0x79

**Comment by cuevavirus** [comment]
The correct value is `0x10000 * 4 / 1080` and it has to be set in the viewport y position.

**Comment by soarqin** [comment]
0x10000 * 4 / 1080 means crop top 4px from original resolution, then the display rect is (0,4)-(960,544), no bottom pixel cropped

**Comment by cuevavirus** [comment]
did you even try it

**Comment by soarqin** [comment]
not yet, I just use your formula to calculate the rect. another way to confirm it: the original transformed height in 1080i is 0x80F3, crop `0x10000 * 4 / 1080` = 0xF3 off top would leave 0x8000, which is `0x10000 * 540 / 1080`, no bottom pixels are cropped.

**Comment by soarqin** [comment]
found a simple way to do it, without additional viewport hooking, tested to be working fine.
precompiled skprx: [sharpscale.zip](https://github.com/cuevavirus/Sharpscale/files/4433049/sharpscale.zip)

patch:
```
diff --git a/main.c.orig b/main.c
index e59c612..686e881 100644
--- a/main.c.orig
+++ b/main.c
@@ -78,7 +78,16 @@ static int sceIftuSetInputFrameBuffer_hook(int plane, SceIftuPlaneState *state,
 		state->dst_x = (1280 - 960) / 2;
 		state->dst_y = (720 - 544) / 2;
 	} else if (state->src_w == 0x8000 && state->src_h == 0x80F3) {
+		unsigned int offset = 0;
 		state->src_h = state->src_w;
+		if (state->fb.pixelformat & 0x0Fu) offset = 2; /* 16bit pixels */
+		else if (state->fb.pixelformat & 0xFFF0u) offset = 4; /* 32bit pixels */
+		if (offset) {
+			offset = (offset * state->fb.width + state->fb.leftover_stride) * 2; /* 2px from 544px */
+			if (state->fb.paddr0) state->fb.paddr0 += offset;
+			if (state->fb.paddr1) state->fb.paddr1 += offset;
+			if (state->fb.paddr2) state->fb.paddr2 += offset;
+		}
 	}
 	return TAI_CONTINUE(int, hook_ref[0], plane, state, mask, mode);
 }

```
NV12/YUV pixel formats are not processed (I dunno how to handle their strides/paddings)

**Comment by frangarcj** [comment]
> 1080p possible in 30hz. I'll add that in the next version

The chip supports 1080p at 60hz unofficially although the config is not in kernel

**Comment by cuevavirus** [comment]
Cropping is now centred

https://forum.devchroma.nl/index.php/topic,112.msg218.html#msg218
