### ISSUE TITLE
Config app crashes

### ISSUE THREAD

**Issue by Peoples00** [cuevavirus/Sharpscale#10]
i can't open the config app it keeps crashing

**Comment by cuevavirus** [comment]
did you install the plugin

**Comment by Peoples00** [comment]
yes

**Comment by cuevavirus** [comment]
disable user plugins for it

https://github.com/cuevavirus/Sharpscale/issues/8#issuecomment-619447699

**Comment by Peoples00** [comment]
I tried but it still crashes
