### ISSUE TITLE
Ps1 scaling on adrenaline

### ISSUE THREAD

**Issue by pedroka26** [cuevavirus/Sharpscale#2]
Already using It and do wonders for 2D games. But what are the best scaling settings on adrenaline now?

**Comment by cuevavirus** [comment]
Please see the new version. I recommend using integer mode with bilinear off.

**Comment by pa-august** [comment]
Messing around with 1080i I'm getting a black screen with Chrono Cross, specifically. I'm guessing a lot of PS1 games are gonna be weird with this mod due to the variable resolutions PS1 games have available to them and can switch between on the fly.

**Comment by cuevavirus** [comment]
If you launch a ps1 game without adrenaline then 1080i mode is not permitted. I'll look into this but for now please use 720p or select something besides original in adrenaline settings.

**Comment by cuevavirus** [comment]
Black screen in 1080i fixed

https://forum.devchroma.nl/index.php/topic,112.msg218.html#msg218
