### ISSUE TITLE
Unable to adjust 'Display Area Settings' in 'Settings/Sound & Display'

### ISSUE THREAD

**Issue by Nostaljaded** [cuevavirus/Sharpscale#3]
As per title, **'Display Area Settings' seems to use the default factory values**, rather than user-adjusted settings.
Hence for my case in 1080i, output is too large (both width & height) to fit in 1920x1080 area.

With Sharpscale plugin disabled, 'Display Area Settings' is still adjustable and obeys user-adjusted settings after h-encore2 activation.

P.S.
Also, **is Sharpscale's current implementation for 1080i mode different from the original 1080i? How so?**
Like 'cropped integer scale progressive mode', instead of e.g. 'bilinear scaling to 1080 interlaced mode'.
My monitor in-display menu is still showing 1080i mode with Sharpscale.

**Comment by cuevavirus** [comment]
The display area setting is at the moment incompatible with the method of scaling I used in this plugin, so I have disabled it.

By default in 1080i, the 960x544 framebuffer is scaled to 1920x1080. This changes the aspect ratio from 30:17 to 16:9 and causes blurriness due to fractional scaling of the height. With sharpscale, the framebuffer is integer scaled to 1920x1088 and the bottom 8 lines are trimmed to create 1920x1080.

The scaling method is independent of the HDMI video mode which remains at 1080i but I will add 1080p 30hz in the next version.

**Comment by cuevavirus** [comment]
The benefit of using sharpscale is a crisp and sharp  image from outputting the original framebuffer, or one that has been integer scaled. That benefit is lost when using display area settings.

**Comment by Nostaljaded** [comment]
Thanks for your explanation.

1 more question:
**So 720p mode is 60hz right?**

With the above answer and your previous replies, good to list them (maybe in bullet points or FAQ style) in the github _README.md_ section for users' reference so that:
- users can easily lookup the answers for such common questions &
- be able determine which display mode is best for them.

Great work! :)

**Comment by cuevavirus** [comment]
All existing HDMI video modes are 60hz.

I already wrote about the features and use cases of sharpscale in the forum post, but I have made it more clear.

**Comment by Tanshaydar** [comment]
I know this is closed but for my TV the display output is too large and I had to use adjustment. Without it being in place, I cannot use this solution.

I know it's incompatible, but is it possible to add this in the future?

**Comment by cuevavirus** [comment]
If you have to downscale the display output then sharpscale won't really provide any benefits.

**Comment by cuevavirus** [comment]
I added to ability to use display area settings if sharpscale is in original mode, if you'd just like to display bilinear filtering.

https://forum.devchroma.nl/index.php/topic,112.msg218.html#msg218
