### ISSUE TITLE
PS1 scaling issue on PSTV

### ISSUE THREAD

**Issue by mrjaredbeta** [cuevavirus/Sharpscale#6]
Hi,

Some PS1 games, such as Tekken 2 and Toy Story Racer, are scaled incorrectly. The width is scaled around twice the length of the height, leaving a rectangular image and incorrect aspect ratio. Other games, such as Silent Hill, are scaled the opposite way, with the height being around double the width. Silent Hill only does this on the main menu/equipment screen, while the ingame and FMVs are fine (and same with Tekken 2's FMVs). I'm guessing this is an issue with games that display variable resolutions?

I am playing through Adrenaline using integer scaling with no bilnear filtering in 1080i output.

**Comment by cuevavirus** [comment]
Indeed that's because many PS1 games use variable resolutions and were designed to be stretched or squished by the TV into 4:3. I can add an option to enforce 4:3 for PS1 games.

**Comment by fbutte** [comment]
It seem that i have the same problem. But i'm using my Vita Slim. I will copy the reply that i post on CBPS Forum:

I'm testing this amazing plugin on my Vita Slim, and when i tried Crash Bandicoot games (the trilogy) they look so tiny and with a forced 16:9 widscreen format compared with other games.

Crash 
https://i.imgur.com/Ph3aGxjl.jpg

Dino Crisis
https://i.imgur.com/QCDgGMml.jpg

Tried +30 other games and the only ones that look like that are the Crash Bandicoot games. Like you say there's more games with variable resolution that look like this. I've tested with 0 0, 1 0 and 2 0 config and all of the look the same.

Maybe the option that you mention to enforce 4:3 for PS1 games could be the solution?

Thanks!

**Comment by xYuunaX** [comment]
also would like to add, games with native widescreen options require some sort of setting to adjust the screen to 16:9. (example: Ghost in the Shell)

**Comment by cuevavirus** [comment]
I'll try making a config app that can run in the background because it'd be annoying to have to restart just to play a game of a different aspect ratio.

**Comment by cuevavirus** [comment]
Fixes in the latest version https://forum.devchroma.nl/index.php/topic,112.0.html
