### ISSUE TITLE
Configuration not working!

### ISSUE THREAD

**Issue by ABOhiccups** [cuevavirus/Sharpscale#7]
I just installed Sharpscale through Autoplugin II on PSTV.

After reboot PSTV. I don't see
ux0:/data/sharpscale/config.txt
or
ur0:/data/sharpscale/config.txt

Even after I created one of these directory alone with config.txt file. It does not work. I reboot PSTV and it starts up with default settings for Sharpscale plugin.

**Comment by cuevavirus** [comment]
Try the new version here with a config app https://forum.devchroma.nl/index.php/topic,112.0.html

**Comment by ABOhiccups** [comment]
It works! I just have to update the plugin manually in order to use config app.

Are you going to release a update on Autoplugin II? So, we don't have to update the plugin manually.

Any chance to add a feature to output native 960x544 without boarders?

**Comment by cuevavirus** [comment]
Good to hear that it's working well. I dont maintain autoplugin but I think they will update it soon on autoplugin. 960x544 without borders might be possible but looks difficult. There are some discussions on #4.
