### ISSUE TITLE
Configuration application failed to start

### ISSUE THREAD

**Issue by zoikun** [cuevavirus/Sharpscale#8]
Somehow configuration app fails to start for no apparent reason, here's error dump, also I could provide additional data about my PSTV if needed.
[psp2core-1587817250-0x00006922af-eboot.bin.psp2dmp.zip](https://github.com/cuevavirus/Sharpscale/files/4532941/psp2core-1587817250-0x00006922af-eboot.bin.psp2dmp.zip)

**Comment by cuevavirus** [comment]
What is your PSTV's system langauge?

**Comment by zoikun** [comment]
It's russian

**Comment by cuevavirus** [comment]
Looks like it's running out of memory while allocating memory for the font, but I can't reproduce this. Can you try this and upload the log at ux0:sharpscale.txt.

[sharpscale_config_test.zip](https://github.com/cuevavirus/Sharpscale/files/4533732/sharpscale_config_test.zip)

**Comment by zoikun** [comment]
Here is log, dump and my config file - maybe one of these plugins could provoke that error
[logs.zip](https://github.com/cuevavirus/Sharpscale/files/4534110/logs.zip)

**Comment by cuevavirus** [comment]
If you disabled it then the config app will crash for sure for a different reason. But from the log the out of memory error happened before that anyway. Maybe one of the plugins allocating memory that it shouldn't. Add this line
```
*!AKRK00005
```
before
```
*ALL
```

**Comment by zoikun** [comment]
I re-enabled Sharpscale and added that line, that you asked me to add, and now application works as intended, here is it's log:
[sharpscale.txt](https://github.com/cuevavirus/Sharpscale/files/4535788/sharpscale.txt)

**Comment by cuevavirus** [comment]
So it's one of the plugins under ALL allocating memory that it shouldn't.
