### ISSUE TITLE
sharpscale plugin does not seem to load

### ISSUE THREAD

**Issue by badsector83** [cuevavirus/Sharpscale#9]
I tried several sharpscale versions (1.1 and 1.2 with config.txt and 1.3 with the config app) with no luck so far.
The sharpscale.skprx is in ur0:tai, the config.txt there has the line "ur0:tai/sharpscale.skprx" just under the line "*KERNEL". I also have no tai folder in ux0: 
By the way, under the line with sharpscale I also added "ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx" which works like a charm.
My PSTV is set to 720p and I do not get the black borders, the config app cannot start, I get patterns with the scalingtest app. Did I miss something? System is on 3.60 CFW by the way.

**Comment by cuevavirus** [comment]
Maybe wrong file path or corrupted file.

**Comment by badsector83** [comment]
I started over the process for around 10 times with different versions from different sources. Is there a way to check if it has been loaded correctly or does it write any log files?

**Comment by cuevavirus** [comment]
Do not use different versions from different sources. Only use the latest version.
Use this attached file and see if there's a log at ur0:sharpscale.txt. If there is no log, then it's a problem with your configuration.
[sharpscale-logged.zip](https://github.com/cuevavirus/Sharpscale/files/4535762/sharpscale-logged.zip)

**Comment by badsector83** [comment]
No sharpscale.txt is written to ur0: unfortunately. There is also no tai folder in ux0: that might get priority for the config.txt

Also my config.txt is super small. Only sharpscale and adrenaline are referenced and adrenaline is working without problems.

![grafik](https://user-images.githubusercontent.com/64361229/80313172-967b1580-87e9-11ea-8e08-02c2b74bb2d2.png)

**Comment by cuevavirus** [comment]
Unfortunately if you cannot get it to load then I can't diagnose this problem further.
